-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.funds
(
    fundid integer NOT NULL,
    userid integer,
    available_balance double precision,
    user_margin double precision,
    last_updated timestamp without time zone,
    CONSTRAINT funds_pkey PRIMARY KEY (fundid),
    UNIQUE (userid)
);

CREATE TABLE IF NOT EXISTS public.instruments
(
    instrumentid integer NOT NULL,
    symbol character varying(255) COLLATE pg_catalog."default",
    exchange character(3) COLLATE pg_catalog."default",
    instrument_type character varying(255) COLLATE pg_catalog."default",
    lot_size integer,
    CONSTRAINT instruments_pkey PRIMARY KEY (instrumentid)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    orderid integer NOT NULL,
    userid integer,
    instrumentid integer,
    order_type character varying(255) COLLATE pg_catalog."default",
    transaction_type character varying(255) COLLATE pg_catalog."default",
    quantity integer,
    price double precision,
    status character varying(255) COLLATE pg_catalog."default",
    order_timestamp timestamp without time zone,
    CONSTRAINT orders_pkey PRIMARY KEY (orderid)
);

CREATE TABLE IF NOT EXISTS public.portfolio
(
    portfolioid integer NOT NULL,
    userid integer,
    instrumentid integer,
    quantity integer,
    average_price double precision,
    current_value double precision,
    pnl numeric(10, 2),
    CONSTRAINT portfolio_pkey PRIMARY KEY (portfolioid)
);

CREATE TABLE IF NOT EXISTS public.users
(
    userid integer NOT NULL,
    username character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    phone integer,
    full_name character varying(255) COLLATE pg_catalog."default",
    pan character(10) COLLATE pg_catalog."default",
    registration_date date,
    CONSTRAINT users_pkey PRIMARY KEY (userid)
);

CREATE TABLE IF NOT EXISTS public.watchlists
(
    watchlistid integer NOT NULL,
    userid integer,
    instrumentid integer,
    watchlist_name character varying(255) COLLATE pg_catalog."default",
    added_date date,
    CONSTRAINT watchlists_pkey PRIMARY KEY (watchlistid)
);

ALTER TABLE IF EXISTS public.funds
    ADD FOREIGN KEY (userid)
    REFERENCES public.users (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_instrumentid_fkey FOREIGN KEY (instrumentid)
    REFERENCES public.instruments (instrumentid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_userid_fkey FOREIGN KEY (userid)
    REFERENCES public.users (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.portfolio
    ADD CONSTRAINT portfolio_instrumentid_fkey FOREIGN KEY (instrumentid)
    REFERENCES public.instruments (instrumentid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.portfolio
    ADD CONSTRAINT portfolio_userid_fkey FOREIGN KEY (userid)
    REFERENCES public.users (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD FOREIGN KEY (userid)
    REFERENCES public.users (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.watchlists
    ADD CONSTRAINT watchlists_instrumentid_fkey FOREIGN KEY (instrumentid)
    REFERENCES public.instruments (instrumentid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.watchlists
    ADD FOREIGN KEY (userid)
    REFERENCES public.users (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;